"""Init

Revision ID: 04314f530d05
Revises: 
Create Date: 2025-06-01 01:28:22.016185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04314f530d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('connector_config_schema', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_definition_key'), ['key'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('action_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_definition_id', sa.Integer(), nullable=False),
    sa.Column('action_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connector_definition_id'], ['connector_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_definition_id', 'action_key', name='_connector_action_key_uc')
    )
    op.create_table('connector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connector_key', sa.String(length=50), nullable=False),
    sa.Column('connection_name', sa.String(length=100), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'connector_key', name='_user_connector_key_uc')
    )
    op.create_table('trigger_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_definition_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('requires_webhook_endpoint', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connector_definition_id'], ['connector_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_definition_id', 'event_key', name='_connector_event_key_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trigger_definition')
    op.drop_table('connector')
    op.drop_table('action_definition')
    op.drop_table('user')
    with op.batch_alter_table('connector_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_definition_key'))

    op.drop_table('connector_definition')
    # ### end Alembic commands ###
