"""add status for Workflow

Revision ID: abb5d3f6ceaa
Revises: 6ccc93064521
Create Date: 2025-06-04 11:32:13.603233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb5d3f6ceaa'
down_revision = '6ccc93064521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
