"""add polling in trigger

Revision ID: e98f067cead5
Revises: abb5d3f6ceaa
Create Date: 2025-06-07 22:47:57.111780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98f067cead5'
down_revision = 'abb5d3f6ceaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trigger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_polled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('polling_state', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trigger', schema=None) as batch_op:
        batch_op.drop_column('polling_state')
        batch_op.drop_column('last_polled_at')

    # ### end Alembic commands ###
